import { Card } from "@mui/material";

const Filters = () => {
    return (
        <div>
            <Card variant='outlined' sx={{
                        height: '100%',
                    }} >
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-duYaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-duYaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-duYaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-duYaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-duYaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-duYaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-duYaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-duYaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
                Yaba-daba-du
            </Card>
        </div>
    )
}

export default Filters;